name: Build and deploy Node.js app to Azure Web App - offerte-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # ⬇️ Install and build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # ⬇️ Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # ⬇️ Copy frontend build to backend
      - name: Move frontend build to backend
        run: |
          cp -r frontend/build backend/build

      # ⬇️ Zip backend (incl. frontend) for deploy
      - name: Zip backend
        working-directory: ./backend
        run: zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_... }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_... }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_... }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'offerte-webapp'
          slot-name: 'Production'
          package: .
